# Generated by Django 4.0.5 on 2022-07-01 03:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourr', '0002_alter_usuario_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='phone',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Telefono Movil'),
        ),
    ]
