# Generated by Django 4.0.5 on 2022-07-07 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourr', '0003_usuario_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viajes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('costo', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'viajes',
                'managed': True,
            },
        ),
    ]
