# Generated by Django 4.0.5 on 2022-07-07 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourr', '0004_viajes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viajes',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
