# Generated by Django 4.0.5 on 2022-07-07 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourr', '0005_alter_viajes_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='viajes',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='viajes'),
        ),
    ]
