# Generated by Django 4.0.5 on 2022-08-12 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourr', '0007_alter_viajes_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lugarturistico',
            fields=[
                ('id_lugar', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('ciudad', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('costo', models.PositiveIntegerField()),
                ('imagen', models.ImageField(upload_to='viajes')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lugarturistico',
                'managed': True,
            },
        ),
    ]
